# Hugging face

auth_token: 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

# CLIP tokenizer and model

clip_model: openai/clip-vit-large-patch14

# Stable diffusion model

diffusion_model: CompVis/stable-diffusion-v1-4



_target_: sce.models.trunks.create_resnet
name: resnet18
num_classes: 0
small_input: True